### ISSUE TITLE
Navegação amigável ao Usuário - READMEs

### ISSUE THREAD

**Issue by GuilhermePalma** [GuilhermePalma/explore_java#1]
## Navegação amigável e README

Atualmente, o repositório não possui READMEs linkados que permitem uma boa navegação do usuário pelo repositório, fazendo com que tenha que navegar pelos diretórios manualmente. 

Dessa forma, é proposto a criação de READMEs dentro de cada escopo de Projeto descrevendo o que aquele `Modulo` tem como objetivo e suas características. Além disso, é necessário que esses READMEs estejam linkados entre si, para que o usuário consiga visualizar de forma visual (nos README) a estrutura e conteúdo disponível no repositório

### Tasks
- [x] Linkar os README Internos dos Projetos com os README Externos
- [x] Alcance das Navegações para cada README
    - [x] Voltar ao diretório do Nivel Anterior e Superior
    - [x] Entrar no diretório do Nivel Superior
    - [x] Voltar ao diretório `root` do Projeto

**Comment by GuilhermePalma** [comment]
## Notification 

**"Desenvolver README relevante para cada Projeto"** task has been moved to another issue (#4)
